OnlineBanking/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "RegisterLogin");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AdminIndex()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "RegisterLogin");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "RegisterLogin");
        }

    }
}

OnlineBanking/Controllers/PayBillController.cs
using OnlineBanking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class PayBillController : Controller
    {
        BankingDBEntities db = new BankingDBEntities();
        // GET: PayBill
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(BillTable Bt)
        {
            if (ModelState.IsValid == true)
            {
                if (Bt.Amount <= Convert.ToDecimal(Session["Balance"]))
                {

                    //To Update Balance at Accounts Table                                           
                    decimal NewBalance = Convert.ToDecimal(Session["Balance"]) - Bt.Amount;
                    int ConvertUserID = Convert.ToInt32(Session["UserID"]);
                    var getAcc = db.AccountsTables.Where(AT => AT.UserID == ConvertUserID).FirstOrDefault();
                    getAcc.Balance = NewBalance;
                    //db.SaveChanges();

                    //To update Bill table
                          
                    Bt.AccountID = Convert.ToInt32(Session["AccountID"]);
                    Bt.PaymentDate = DateTime.Now;
                    db.BillTables.Add(Bt);
                    int a = db.SaveChanges();

                    //To record transactions
                    TransactionsTable TT = new TransactionsTable();
                    TT.AccountID = Convert.ToInt32(Session["AccountID"]);
                    TT.TransactionType = "Bill Payment";                   
                    TT.Amount = Bt.Amount;
                    TT.TransactionDate = DateTime.Now;
                    TT.Description = Bt.BillType;
                    db.TransactionsTables.Add(TT);
                    //db.SaveChanges();

                    StatementTable STB = new StatementTable();
                    STB.ThisAccount = Convert.ToInt32(Session["AccountID"]);
                    STB.TDate = DateTime.Now;
                    STB.FromAccount = Session["AccountNo"].ToString();
                    STB.ToAccount = "-";
                    STB.Type = "Bill Payment";
                    STB.OldBalance = Convert.ToInt32(Session["Balance"]);
                    STB.Amount = Convert.ToInt32(Session["Balance"]);
                    STB.NewBalance = Convert.ToInt32(Bt.Amount);
                    db.StatementTables.Add(STB);
                    db.SaveChanges();
                    (Session["Balance"]) = NewBalance;                
                    if (a > 0)
                    {
                        ViewBag.ErrorMessage = "<script>alert('Bill Payment Successful!!')</script>";
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "<script>alert('Bill Payment Failed!!')</script>";
                        return View();
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "<script>alert('Insufficient Balance!!')</script>";
                    return View();
                }
                return View();

            }
            return View();

        }
    }
}

OnlineBanking/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineBanking.Models;

namespace OnlineBanking.Controllers
{
    public class TransactionsController : Controller
    {
        private BankingDBEntities db = new BankingDBEntities();

        // GET: Transactions
        public ActionResult Index(DateTime? dateFrom, DateTime? dateTo)
        {
            string CurrentUser = Session["AccountNo"].ToString();

            // It will make sure that the user can only see their Account Statement
            var transactions = db.TransactionsTables
                                .Include(t => t.AccountsTable)
                                .Where(t => t.AccountsTable.AccountNumber == CurrentUser);

            // Apply date filters if specified
            if (dateFrom.HasValue)
            {
                transactions = transactions.Where(t => t.TransactionDate >= dateFrom.Value);
            }

            if (dateTo.HasValue)
            {
                transactions = transactions.Where(t => t.TransactionDate <= dateTo.Value);
            }

            return View(transactions.ToList());
        }


        public ActionResult Detailed(DateTime? dateFrom, DateTime? dateTo)
        {
            int CurrentUser = Convert.ToInt32(Session["AccountID"]);

            // It will make sure that the user can only see their Account Statement
            var transactions = db.StatementTables
                                .Include(ST => ST.AccountsTable)
                                .Where(ST => ST.AccountsTable.AccountID == CurrentUser);

            // Apply date filters if specified
            if (dateFrom.HasValue)
            {
                transactions = transactions.Where(t => t.TDate >= dateFrom.Value);
            }

            if (dateTo.HasValue)
            {
                transactions = transactions.Where(t => t.TDate <= dateTo.Value);
            }

            return View(transactions.ToList());
        }


        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionsTable transactionsTable = db.TransactionsTables.Find(id);
            if (transactionsTable == null)
            {
                return HttpNotFound();
            }
            return View(transactionsTable);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            ViewBag.AccountID = new SelectList(db.AccountsTables, "AccountID", "AccountNumber");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TID,AccountID,TransactionType,Amount,TransactionDate,Description")] TransactionsTable transactionsTable)
        {
            if (ModelState.IsValid)
            {
                db.TransactionsTables.Add(transactionsTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountID = new SelectList(db.AccountsTables, "AccountID", "AccountNumber", transactionsTable.AccountID);
            return View(transactionsTable);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionsTable transactionsTable = db.TransactionsTables.Find(id);
            if (transactionsTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccountID = new SelectList(db.AccountsTables, "AccountID", "AccountNumber", transactionsTable.AccountID);
            return View(transactionsTable);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TID,AccountID,TransactionType,Amount,TransactionDate,Description")] TransactionsTable transactionsTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transactionsTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccountID = new SelectList(db.AccountsTables, "AccountID", "AccountNumber", transactionsTable.AccountID);
            return View(transactionsTable);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionsTable transactionsTable = db.TransactionsTables.Find(id);
            if (transactionsTable == null)
            {
                return HttpNotFound();
            }
            return View(transactionsTable);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TransactionsTable transactionsTable = db.TransactionsTables.Find(id);
            db.TransactionsTables.Remove(transactionsTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineBanking/Views/PayBill/Index.cshtml
@model OnlineBanking.Models.BillTable

@{
    ViewBag.Title = "Index";
}
@Html.Raw(ViewBag.ErrorMessage)
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/admin/admin_dashboard/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" crossorigin="anonymous" />
</head>
<body class="sb-nav-fixed">


    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Digital Banking</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="@Url.Action( "Logout", "Dashboard")">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">

                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action( "Index", "Dashboard")">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Home
                        </a>
                        <div class="sb-sidenav-menu-heading">TRANSACTIONS</div>
                        <a class="nav-link" href="@Url.Action( "Index", "TransferMoney")">
                            <div class="sb-nav-link-icon"><i class="fas fa-exchange-alt"></i></div>
                            Transfer Money
                        </a>
                        <a class="nav-link" href="#">
                            <div class="sb-nav-link-icon"><i class="fas fa-money-check"></i></div>
                            Bill Payment
                        </a>
                        <div class="sb-sidenav-menu-heading">HISTORY</div>
                        <a class="nav-link" href="@Url.Action( "Index", "Transactions")">
                            <div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
                            Statement
                        </a>
                        <a class="nav-link" href="@Url.Action( "Balance", "TransferMoney")">
                            <div class="sb-nav-link-icon"><i class="fas fa-money-bill-wave"></i></div>
                            Account Balance
                        </a>
                    </div>
                </div>

                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as: @Session["FirstName"]</div>
                    Digital Banking
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h1 class="mt-4">Account No:  @Session["AccountNo"]</h1>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active">"Pay bills easily from the comfort of your home."</li>
                    </ol>



@using (Html.BeginForm("Index", "PayBill", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <!-- Bill Details Section -->
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading" style="background-color: #87CEFA; text-align: center; border-radius: 5px;">
                        <!-- Light blue background -->
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Bill Details
                    </div>
                    <div class="panel-body">
                        <div class="form-group row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.BillType, htmlAttributes: new { @class = "control-label" })
                                <div>
                                    @Html.DropDownListFor(model => model.BillType, new SelectList(new[] { "Water", "Electricity", "Gas", "Internet" }), "Select Bill Type", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.BillType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Amount, "Amount to Pay", htmlAttributes: new { @class = "control-label" })
                                <div>
                                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Amount" } })
                                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.PaymentDate, "Payment Date", htmlAttributes: new { @class = "control-label" })
                                <div>
                                    <input asp-for="PaymentDate" class="form-control" id="paymentDateField" readonly placeholder="Select Date" />
                                    @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <br>
                            <br>
                            <br>
                            <br>
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-check" aria-hidden="true"></span> Confirm Payment
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


           
        </div>
    </div>
}

                </div>
            </main>

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Digital Banking 2024</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
    </div>

    </form>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin/admin_dashboard/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/datatables-demo.js"></script>

</body>
</html>
@section scripts {
    <!-- Bootstrap Datepicker -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#paymentDateField').datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
                clearBtn: true,
                startDate: new Date(),
                endDate: new Date()
            });
        });
    </script>
}